account/urls.py
from django.contrib.auth.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.registration_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('account/', views.account_view, name='account')
]

delight/urls.py
from django.urls import path
from . import views
from .views import SearchResultsView

app_name = 'delight'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('about-us/', views.about_us, name='about_us'),
    path('store/', views.store, name='store'),
    path('product/<int:product_id>/', views.product, name='product'),
    path('category/<int:category_id>/', views.category, name='category'),
    path('savings-product/<int:product_id>/', views.savings_product, name='savings_product'),
    path('search-results/', SearchResultsView.as_view(), name='search_results'),
    path('mobile-search/', views.mobile_search, name='mobile_search'),
]

digital_delight/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('delight.urls')),
    path('account/', include('account.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

delight/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(default='Check out the high quality products that we have.')
    image = models.ImageField(upload_to='uploads/')


    class Meta:
        verbose_name_plural = 'Categories'


    def __str__(self):
        return self.name  


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.CharField(max_length=100, default='$')
    image1 = models.ImageField(upload_to='uploads/')
    image2 = models.ImageField(upload_to='uploads/')
    image3 = models.ImageField(upload_to='uploads/')
    image4 = models.ImageField(upload_to='uploads/')
    date_posted = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name 


class SavingsProduct(models.Model):
    category = models.ForeignKey(Category, related_name='savings_product', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    price_before = models.CharField(max_length=100, default='$')
    price_now = models.CharField(max_length=100, default='$')
    image1 = models.ImageField(upload_to='uploads/')
    image2 = models.ImageField(upload_to='uploads/')
    image3 = models.ImageField(upload_to='uploads/')
    image4 = models.ImageField(upload_to='uploads/')
    date_posted = models.DateTimeField(auto_now_add=True)

    
    def __str__(self):
        return self.name 

delight/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Category, Product, SavingsProduct
from django.views.generic import TemplateView, ListView
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required
def index(request):
    category_list = Category.objects.order_by('-id')
    product_list = Product.objects.order_by('-date_posted')
    savings_products_list = SavingsProduct.objects.order_by('-date_posted')
    paginator = Paginator(category_list, 3) # 3 categories in each page
    paginator2 = Paginator(product_list, 8) # 3 categories in each page
    paginator3 = Paginator(savings_products_list, 8) # 3 categories in each page
    page = request.GET.get('page')
    try:
        categories = paginator.page(page)
        products = paginator2.page(page)
        savings_products = paginator3.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        categories = paginator.page(1)
        products = paginator2.page(1)
        savings_products = paginator3.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        categories = paginator.page(paginator.num_pages)
        products = paginator2.page(paginator.num_pages)
        savings_products = paginator3.page(paginator.num_pages)
        
    
    context = {
        'categories': categories,
        'page': page,
        'products': products,
        'savings_products': savings_products
    }
    return render(request, 'delight/index.html', context)

@login_required
def about_us(request):
    return render(request, 'delight/about_us.html')


@login_required
def contact_us(request):
    return render(request, 'delight/contact_us.html')


@login_required
def store(request):
    category_list = Category.objects.order_by('-id')
    product_list = Product.objects.order_by('-date_posted')
    savings_products_list = SavingsProduct.objects.order_by('-date_posted')
    paginator = Paginator(category_list, 5) # 3 categories in each page
    paginator2 = Paginator(product_list, 12) # 3 categories in each page
    page = request.GET.get('page')
    try:
        categories = paginator.page(page)
        products = paginator2.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        categories = paginator.page(1)
        products = paginator2.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        categories = paginator.page(paginator.num_pages)
        products = paginator2.page(paginator.num_pages)
        
    # products = Product.objects.all()
    # categories = Category.objects.all()
    context = {'products': products, 'categories': categories}
    return render(request, 'delight/store.html', context)


@login_required
def product(request, product_id):
    product = Product.objects.get(id=product_id)
    products = Product.objects.filter(category=product.category)
    context = {'product': product, 'products': products}
    return render(request, 'delight/product.html', context)


@login_required
def category(request, category_id):
    category = Category.objects.get(id=category_id)
    products = category.product.all()
    context = {'category': category, 'products': products}
    return render(request, 'delight/category.html', context)



@login_required
def savings_product(request, product_id):
    product = SavingsProduct.objects.get(id=product_id)
    products = SavingsProduct.objects.filter(category=product.category)
    context = {'product': product, 'products': products}
    return render(request, 'delight/savings_product.html', context)


class SearchResultsView(ListView):
    model = Product
    template_name = 'delight/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Product.objects.filter(
        Q(name__icontains=query) 
        )
        return object_list


@login_required
def mobile_search(request):
    return render(request, 'delight/mobile_search.html')

delight/templates/delight/about_us.html
{% extends 'delight/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}About Us{% endblock title %}
</head>
<body>
    {% block content %}
        <section style="background-image:linear-gradient(rgba(0, 0, 0, 0.527),rgba(0, 0, 0, 0.5)), url({% static '/images/clay-banks-XvS-uKUoUao-unsplash.jpg' %});" class="top-container">
            <div class="top-container-info">
                <h1>About Us</h1>
                <p>We offer the best electronic gadgets<br>at accessible prices.</p>
            </div>

        </section>

        <div class="top-info">
            <h4>We are Digital Delight</h4>
            <h1>Since 2018, our goal has been to deliver the best<br>technology to the society.</h1>
        </div>

        <section class="business-info">
            <div class="feature">
                <div class="feature-top">
                    <i class="fas fa-users"></i>
                    <h2>Customer Support</h2>
                </div>

                <div class="feature-bottom">
                    <p>We offer 24/7 customer support for our services.  You can contact us at available contact details using the methods available i.e Whaatsapp</p>
                </div>
            </div>

            <div class="feature">
                <div class="feature-top">
                    <i class="fas fa-users"></i>
                    <h2>Free Delivery</h2>
                </div>

                <div class="feature-bottom">
                    <p>Our company partakes in the free delivery sevices.  After ordering the product that you want, you give the details of where you want it delivered.</p>
                </div>
            </div>

            <div class="feature">
                <div class="feature-top">
                    <i class="fas fa-users"></i>
                    <h2>Safety Guaranteed</h2>
                </div>

                <div class="feature-bottom">
                    <p>Our products are of the highest quality and with that comes highest durability and safety for the user.  Hence safety for the user is always guranteed,</p>
                </div>
            </div>
        </section>

        <div class="bottom-info">
            <h1 style="color: var(--color);">Business Hours</h1>
            <div class="location-stores">
                <h4>Mt Pleasant, Groombridge</h4>
                <h4>Highlands, Portal 1 Shop 27</h4>
            </div>
            <div class="time-info">

                <div class="time-info-schedule">
                    <div class="days">
                        <h3>Mon - Fri</h3>
                        <h3>Sat</h3>
                        <h3>Sun</h3>
                    </div>
                    <div class="time">
                        <h3>0830hrs - 1630hrs</h3>
                        <h3>0830hrs - 1530hrs</h3>
                        <h3>Closed</h3>
                    </div>   
                </div>

                <div class="campaign">
                    <img src="{% static '/images/IMG-20221031-WA0014.jpg' %}" alt="">
                </div>

            </div>
        </div>

        <section class="banner">

            <div class="banner-info">
            <h1>Lets Talk</h1>
            <p>Feel free to get in touch with us<br>if you have any questions.</p>
            <a href="{% url 'delight:contact_us' %}" class="btn">Contact Us</a>
            </div>

        </section>
    {% endblock content %}    
</body>
</html>

delight/templates/delight/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/style.css' %}">
    <link rel="stylesheet" href="{% static '/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static '/font-6/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static '/font-6/css/fontawesome.min.css' %}">
    <title>{% block title %}{% endblock title %}</title>
    <script
    src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
</head>
<body>
    <header class="H1">
        <image class="logo" src="{% static '/images/IMG-20221031-WA0014.jpg' %}"></image>
        <form action="{% url 'delight:search_results' %}" method="get">
            <div class="search-nav-bar">
                <input name="q" type="text" placeholder="Search...">
                <!-- <a href=""><i class="fas fa-search"></i></a> -->
            </div>
        </form>

        <div class="user-location">
            <i class="fa-solid fa-location-dot"></i>
            <div class="location-stores">
                <h5>Mt Pleasant, Groombridge</h5>
                <h5>Highlands, Portal 1 Shop 27</h5>
            </div>
        </div>

        <div class="nav-tab">
            <div class="sml-search">
                <a href="{% url 'delight:mobile_search' %}"><i class="fas fa-search"></i></a>
            </div>
        {% if request.user.is_authenticated %}
            <div class="user">
                <a href="{% url 'account:logout' %}" class="btn">Sign Out</a>
            </div>
        {% else %}
            <div class="user">
                <a href="{% url 'account:login' %}" class="btn">Sign In</a>
            </div>
        {% endif %}
        </div>

        <div class="sml-nav">
            <div class="sml-search">
                <a href="{% url 'delight:mobile_search' %}"><i class="fas fa-search"></i></a>
            </div>

            <div class="sml-nav-2">

                <button class="mobile-toggle" 
                aria-controls="pry-nav" aria-expanded="false">
                <span class="sr-only">Menu</span>
            </button>

            <nav>
                <ul id="pry-nav" data-visible="false" class="pry-nav">
                    <div class="profile-acc">
                        <img src="{% static '/images/log2.jpg' %}" alt="">
                        {% if request.user.is_authenticated %}
                            <div class="profile-acc-details">
                                <h2><span><i class="fas fa-user"></i></span>Sign Out</h2>
                                <a href="{% url 'account:logout' %}">Log Out</a>
                            </div>
                        {% else %}
                            <div class="profile-acc-details">
                                <h2><span><i class="fas fa-user"></i></span>Sign In/Up</h2>
                                <a href="{% url 'account:login' %}">Log In</a>
                            </div>
                        {% endif %}
                    </div>
                    <li><a href="{% url 'delight:index' %}"><span><i class="fas fa-users"></i></span> Home</a></li>
                    <li><a href="{% url 'delight:about_us' %}"><span><i class="fas fa-users"></i></span> About Us</a></li>
                    <li><a href="{% url 'delight:store' %}"><span> <i class="fas fa-images"></i></span> Store</a></li>
                    <li><a href="{% url 'delight:contact_us' %}"><span><i class="fas fa-store"></i></span> Contact Us</a></li>
                    
                    <div class="user-location user-location-beta">
                        <i class="fa-solid fa-location-dot"></i>
                        <div class="location-stores">
                            <h5>Mt Pleasant, Groombridge</h5>
                            <h5>Highlands, Portal 1 Shop 27</h5>
                        </div>
                    </div>
                </ul>
            </nav>
            </div> 
        </div>

    </header>

    <header class="H2">
        <nav class="nav-bar">
            <ul>
                <li><a href="{% url 'delight:index' %}">Home</a></li>
                <li><a href="{% url 'delight:about_us' %}">About Us</a></li>
                <li><a href="{% url 'delight:store' %}">Store</a></li>
                <li><a href="{% url 'delight:contact_us' %}">Contact Us</a></li>
            </ul>
        </nav>
    </header>
   
    {% block content %}
    {% endblock content %}
    <footer class="featured foot-det">
        <div class="col">
            <h1>Let's Get Digital</h1>

            <div class="follow">
                <h3>Follow Us</h3>
                <div class="vendor-tag">
                    <i style="color: white;" class="fab fa-facebook-f"></i>
                    <i style="color: white;" class="fab fa-instagram"></i>
                </div>
            </div>
        </div>

        <div class="col">
            <h3>About</h3>
            <a href="{% url 'delight:about_us' %}">About Us</a>
            <a href="{% url 'delight:about_us' %}">Terms & Conditions</a>
            <a href="{% url 'delight:about_us' %}">Privacy Policy</a>
        </div>

        <div class="col">
            <h3>My Account</h3>
            {% if request.user.is_authenticated %}
                <a href="{% url 'account:logout' %}">Sign Out</a>
            {% else %}
                <a href="{% url 'account:login' %}">Sign In</a>
            {% endif %}
            <a href="{% url 'delight:contact_us' %}">Contact Us</a>
        </div>

        <section class="line">
            <p>Copyright 2022 @Digital Delight. All rights reserved.</p>
        </section>
        
    </footer>


    <script src="{% static '/main2.js' %}" defer></script>
    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
    <script type="text/javascript">
        $('.main-carousel').flickity({
            cellAlign: 'left',
            wrapAround:true,
            freeScroll: true
        });
    </script> 
    
</body>
</html>

delight/templates/delight/category.html
{% extends 'delight/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{{ category.name }}{% endblock title %}
</head>
<body>
    {% block content %}
        <section style="background-image:linear-gradient(rgba(0, 0, 0, 0.527),rgba(0, 0, 0, 0.5)), url({{ category.image.url }});" class="top-container">
            <div class="top-container-info">
                <h5>{{ category.name }}.</h5>
                <h1>Store Gallery</h1>
                <p>Check out our latest {{ category.name }}<br>at accessible prices.</p>
            </div>
        </section>

        <section class="product-items">
            {% for product in products %}
                <div class="product">
                    <div class="product-content">
                        <div class="product-img">
                            <img src="{{ product.image1.url }}" alt="" onclick="window.location.href='{% url 'delight:product' product.id %}';">
                        </div>

                        <div class="product-info">
                            <div class="product-info-top" onclick="window.location.href='{% url 'delight:product' product.id %}';">
                                <h5>{{ product.category }}</h5>
                            </div>

                            <div class="product-info-bottom" onclick="window.location.href='{% url 'delight:product' product.id %}';">
                                <h2 class="name">{{ product.name }}</h2>
                                <h2 class="price">{{ product.price }}</h2>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </section>
    {% endblock content %}
    
</body>
</html>

delight/templates/delight/index.html
{% extends 'delight/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %} Home {% endblock title %}
</head>
<body>
    {% block content %}
    <section class="top-container">
        <div class="top-container-info">
            <h1>Lets Get Digital</h1>
            <p>We offer the best electronic gadgets<br>at accessible prices.</p>
            <a href="{% url 'delight:store' %}" class="btn">Shop Now</a>
        </div>

    </section>

    <section class="top">
        {% for category in categories %}

            <div style="background-image:linear-gradient(rgba(0, 0, 0, 0.527),rgba(0, 0, 0, 0.5)), url({{category.image.url}});" class="top-banter">
                <h4>{{ category.name }}</h4>
                <p>{{ category.description }}</p>
                <a href="{% url 'delight:category' category.id %}" class="btn-cat">Shop Now</a>
            </div>

        {% endfor %}

       
    </section>

    <div class="topic">
        <h5>Hot Items</h5>
        <h1>New Arrivals</h1>
    </div>

    <section class="product-items">
        {% for product in products %}
        <div class="product">
            <div class="product-content">
                <div class="product-img">
                    <img src="{{ product.image1.url }}" alt="" onclick="window.location.href='{% url 'delight:product' product.id %}';">
                </div>

                <div class="product-info">
                    <div class="product-info-top">
                        <h5>{{ product.category }}</h5>
                    </div>

                    <div class="product-info-bottom">
                        <h2 class="name">{{ product.name }}</h2>
                        <h2 class="price">{{ product.price }}</h2>
                    </div>
                </div>
            </div>
        </div>

        {% endfor %}

    </section>

    <section class="banner">

        <div class="banner-info">
        <h1>Introducing Virtual Reality</h1>
        <p>Get up to fast with the best technology<br>so as to enhance your experience</p>
        <a href="{% url 'delight:store' %}" class="btn">Shop Now</a>
        </div>

    </section>

    <div class="topic">
        <h5>Grab Fast</h5>
        <h1>Featured Savings</h1>
    </div>

    <section class="product-items">
        {% for product in savings_products %}
            <div class="product">
                <div class="product-content">
                    <div class="product-img">
                        <img src="{{ product.image1.url }}" alt="" onclick="window.location.href='{% url 'delight:savings_product' product.id %}';">
                    </div>

                    <div class="product-info">
                        <div class="product-info-top" onclick="window.location.href='{% url 'delight:savings_product' product.id %}';">
                            <h5>{{ product.category }}</h5>
                        </div>

                        <div class="product-info-bottom"onclick="window.location.href='{% url 'delight:savings_product' product.id %}';">
                            <h2 class="name">{{ product.name }}</h2>
                            <div class="price-tags">
                            <h2 class="old-price">{{ product.price_before }}</h2>
                            <h2 class="price">{{ product.price_now }}</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    
        {% endfor %}
    </section>

    <section class="top">
        {% for category in categories %}
            <div style="background-image:linear-gradient(rgba(0, 0, 0, 0.527),rgba(0, 0, 0, 0.5)), url({{category.image.url}});" class="top-banter">
                <h4>{{ category.name }}</h4>
                <p>{{ category.description }}</p>
                <a href="{% url 'delight:category' category.id %}" class="btn-cat">Shop Now</a>
            </div>
        {% endfor %}

    
        
    </section>

    <div class="topic">
        <h5>This Week</h5>
        <h1>Trending</h1>
    </div>

    <section class="trending-items">
        <div class="hot-item">
            <h4>All the latest gadgets</h4>
            <h2>At an affordable price!!</h2>
        </div>

        <div class="other-items other-items-alpha">
            <div class="product-items beta">
                {% for product in products %}
                <div class="product">
                    <div class="product-content">
                        <div class="product-img">
                            <img src="{{ product.image1.url }}" alt="" onclick="window.location.href='{% url 'delight:product' product.id %}';">
                        </div>
        
                        <div class="product-info">
                            <div class="product-info-top" onclick="window.location.href='{% url 'delight:product' product.id %}';">
                                <h5>{{ product.category }}</h5>
                            </div>
        
                            <div class="product-info-bottom" onclick="window.location.href='{% url 'delight:product' product.id %}';">
                                <h2 class="name">{{ product.name }}</h2>
                                <h2 class="price">{{ product.price }}</h2>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
        
               
        
        
               
        </div>
        </section>
    {% endblock content %}
</body>
</html>

delight/templates/delight/mobile_search.html
{% extends 'delight/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% block title %}Search{% endblock title %}
</head>
<body>
    {% block content %}
    <section class="log-in-form"> 
        <div class="sign-up sign-up-beta">
            <header>
                <h1>Search Here</h1>
                <p>Enter a keyword to search for the product that you want from our catalogue.</p>
            </header>
    
            <div class="form-outer">
                <form action="{% url 'delight:search_results' %}" method="get">
                    <div class="sign-page slidepage">
      
                    <div class="input-field">
                        <input name="q" type="text" placeholder="Enter Keyword">
                    </div>
                 </div> 
                </form>
            </div>
        </div>
       </section>
    {% endblock content %}
</body>
</html>

delight/templates/delight/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

delight/templates/delight/search_results.html
{% extends 'delight/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}Search Results{% endblock title %}
</head>
<body>
    {% block content %}

        <section class="product-items">
            {% for product in object_list %}
                <div class="product">
                    <div class="product-content">
                        <div class="product-img">
                            <img src="{{ product.image1.url }}" alt="" onclick="window.location.href='{% url 'delight:product' product.id %}';">
                        </div>

                        <div class="product-info">
                            <div class="product-info-top" onclick="window.location.href='{% url 'delight:product' product.id %}';">
                                <h5>{{ product.category }}</h5>
                            </div>

                            <div class="product-info-bottom" onclick="window.location.href='{% url 'delight:product' product.id %}';">
                                <h2 class="name">{{ product.name }}</h2>
                                <h2 class="price">{{ product.price }}</h2>
                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                <li>Oops!  Search didn't yield any results</li>
            {% endfor %}

        </section>
    {% endblock content %}
    
</body>
</html>

delight/templates/delight/store.html
{% extends 'delight/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}Store{% endblock title %}
</head>
<body>
    {% block content %}
        <section  style="background-image:linear-gradient(rgba(0, 0, 0, 0.527),rgba(0, 0, 0, 0.5)), url({% static '/images/laurenz-heymann-VkfhJLz5SMQ-unsplash.jpg' %});" class="top-container">
            <div class="top-container-info">
                <h5>Products.</h5>
                <h1>Store Gallery</h1>
                <p>Check out our latest gadegts<br>at accessible prices.</p>
            </div>
        </section>

        <section class="product-line">
            
            <div class="product-categories">
                {% for category in categories %}
                    <div style="background-image:linear-gradient(rgba(0, 0, 0, 0.527),rgba(0, 0, 0, 0.5)), url({{category.image.url}});" class="cat-banter">
                        <h4>{{ category.name }}</h4>
                        <p>{{ category.description }}</p>
                        <a href="{% url 'delight:category' category.id %}" class="btn-cat">Shop Now</a>
                    </div>
                {% endfor %}

            </div>


            <div class="other-items other-items-beta">
                <div class="product-items beta">
                    {% for product in products %}
                        <div class="product">
                            <div class="product-content">
                                <div class="product-img">
                                    <img src="{{ product.image1.url }}" alt="" onclick="window.location.href='{% url 'delight:product' product.id %}';">
                                </div>
                
                                <div class="product-info">
                                    <div class="product-info-top" onclick="window.location.href='{% url 'delight:product' product.id %}';">
                                        <h5>{{ product.category }}</h5>
                                    </div>
                
                                    <div class="product-info-bottom" onclick="window.location.href='{% url 'delight:product' product.id %}';">
                                        <h2 class="name">{{ product.name }}</h2>
                                        <h2 class="price">{{ product.price }}</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
            
            

               
            
                
        
    
                </div>
                
            </div>
        </section>
        {% include "delight/pagination.html" with page=products %}

        <section class="banner">

            <div class="banner-info">
            <h1>Introducing Virtual Reality</h1>
            <p>Get up to fast with the best technology<br>so as to enhance your experience</p>
            <a href="{% url 'delight:store' %}" class="btn">Shop Now</a>
            </div>

        </section>

        
 
  
    {% endblock content %}
</body>
</html>